[projects."github.com/MetechDevelopment/interal"]
approved-commands = [
    """
opencode run "/preflight"
""",
    """
composer install
""",
    "composer fix",
    "composer test",
    """
opencode --prompt "/ship"
""",
    """
opencode run "/ship"
""",
    """
opencode run --agent reviewer "/ship"
""",
    """
opencode run --agent reviewer "/preflight"
""",
    """
npm install
npm run build
""",
    """
npm install && npm run build
""",
    """
npm run build
""",
]

[projects."github.com/rsenses/Direccion-Deportiva"]
approved-commands = [
    """
opencode run "/preflight"
""",
    """
composer install
""",
    "composer fix",
    "composer test",
    """
opencode --prompt "/ship"
""",
    """
opencode run --agent reviewer "/preflight"
""",
    """
npm install && npm run build
""",
    """
npm run build
""",
    """
opencode run "/ship"
""",
    """
opencode run --agent reviewer "/ship"
""",
    """
npm install
npm run build
""",
]

[projects."gitlab.com/expomark/eventark"]
approved-commands = [
    """
opencode run "/preflight"
""",
    """
composer install
""",
]
