live_config_reload = true

import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"
# args = [ "-c", "'t'" ]

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
blur = true

[window.padding]
x = 0
y = 0
