#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/zsh
ln -sf $DOTFILES/zsh/.zshrc $HOME/.zshrc
ln -s $DOTFILES/zsh $HOME/.config/zsh

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/nvim.bak
ln -s $DOTFILES/nvim.bak $HOME/.config/nvim.bak

rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/wezterm
ln -s $DOTFILES/wezterm $HOME/.config/wezterm

rm -rf $HOME/.config/tmux
ln -sf $DOTFILES/tmux $HOME/.config/tmux

rm -rf $HOME/.config/yabai
ln -sf $DOTFILES/yabai $HOME/.config/yabai

rm -rf $HOME/.config/vifm
ln -sf $DOTFILES/vifm $HOME/.config/vifm

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

ln -sf $DOTFILES/git/gitignore $HOME/.gitignore

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
chmod +x $HOME/.local/bin/t

rm -rf $HOME/.tmux-cht-languages
ln -sf $DOTFILES/tmux/.tmux-cht-languages $HOME/.tmux-cht-languages

rm -rf $HOME/.tmux-cht-command
ln -sf $DOTFILES/tmux/.tmux-cht-command $HOME/.tmux-cht-command

rm -rf $HOME/.local/bin/tmux-cht.sh
ln -sf $DOTFILES/scripts/tmux-cht.sh $HOME/.local/bin/tmux-cht.sh
chmod +x $HOME/.local/bin/tmux-cht.sh
