#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/zsh
rm -rf $HOME/.zshenv
ln -sf $DOTFILES/zsh/zshenv $HOME/.zshenv
ln -sf $DOTFILES/zsh/zprofile $DOTFILES/zsh/.zprofile
ln -sf $DOTFILES/zsh/zshrc $DOTFILES/zsh/.zshrc
ln -s $DOTFILES/zsh $HOME/.config/zsh

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/tmux
ln -sf $DOTFILES/tmux $HOME/.config/tmux

rm -rf $HOME/.config/ghostty
ln -sf $DOTFILES/ghostty $HOME/.config/ghostty

rm -rf $HOME/.config/rofi
ln -s $DOTFILES/rofi $HOME/.config/rofi

rm -rf $HOME/.config/sesh
ln -sf $DOTFILES/sesh $HOME/.config/sesh

rm -rf $HOME/.gitconfig
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

rm -rf $HOME/.gitignore
ln -sf $DOTFILES/git/gitignore $HOME/.gitignore

rm -rf $HOME/.Xresources
ln -sf $DOTFILES/.Xresources $HOME/.Xresources

rm -rf $HOME/.config/awesome
ln -s $DOTFILES/awesome $HOME/.config/awesome

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/ide
ln -sf $DOTFILES/scripts/ide $HOME/.local/bin/ide
chmod +x $HOME/.local/bin/ide

rm -rf $HOME/.local/bin/home
ln -sf $DOTFILES/scripts/home $HOME/.local/bin/home
chmod +x $HOME/.local/bin/home

rm -rf $HOME/.tmux-cht-languages
ln -sf $DOTFILES/tmux/.tmux-cht-languages $HOME/.tmux-cht-languages

rm -rf $HOME/.tmux-cht-command
ln -sf $DOTFILES/tmux/.tmux-cht-command $HOME/.tmux-cht-command

rm -rf $HOME/.local/bin/tmux-cht.sh
ln -sf $DOTFILES/scripts/tmux-cht.sh $HOME/.local/bin/tmux-cht.sh
chmod +x $HOME/.local/bin/tmux-cht.sh

rm -rf $HOME/.local/bin/rofi-power-menu
ln -sf $DOTFILES/scripts/rofi-power-menu $HOME/.local/bin/rofi-power-menu
chmod +x $HOME/.local/bin/rofi-power-menu

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.editorconfig
ln -sf $DOTFILES/.editorconfig $HOME/.editorconfig
