#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/zsh
ln -s $DOTFILES/zsh $HOME/.config/zsh
ln -sf $DOTFILES/zsh/zshrc-linux $HOME/.config/zsh/.zshrc
ln -sf $DOTFILES/zsh/zshenv $HOME/.zshenv

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/awesome
ln -s $DOTFILES/nvim $HOME/.config/awesome

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/tmux
ln -sf $DOTFILES/tmux $HOME/.config/tmux

ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

ln -sf $DOTFILES/git/gitignore $HOME/.gitignore

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
chmod +x $HOME/.local/bin/t

rm -rf $HOME/.tmux-cht-languages
ln -sf $DOTFILES/tmux/.tmux-cht-languages $HOME/.tmux-cht-languages

rm -rf $HOME/.tmux-cht-command
ln -sf $DOTFILES/tmux/.tmux-cht-command $HOME/.tmux-cht-command

rm -rf $HOME/.local/bin/tmux-cht.sh
ln -sf $DOTFILES/scripts/tmux-cht.sh $HOME/.local/bin/tmux-cht.sh
chmod +x $HOME/.local/bin/tmux-cht.sh

rm -rf $HOME/.editorconfig
ln -sf $DOTFILES/.editorconfig $HOME/.editorconfig
