vim.bo.commentstring = '<!-- %s -->'
vim.opt_local.spell = true
vim.opt_local.conceallevel = 0
vim.opt_local.number = false
vim.opt_local.relativenumber = false
vim.opt_local.tabstop = 2
vim.opt_local.shiftwidth = 2
vim.opt_local.softtabstop = 2
vim.opt_local.wrap = true
vim.opt_local.textwidth = 80
vim.opt_local.linebreak = true
