use_nerdfont = true
initial_screen = "queue"

[theme]
background = "default"
primary = "foreground"
secondary = "light black"
title = "primary"
playing = "black"
playing_selected = "primary"
playing_bg = "white"
highlight = "foreground"
highlight_bg = "light black"
error = "#FFE4E4"
error_bg = "#A8334C"
statusbar = "white"
statusbar_progress = "primary"
statusbar_bg = "light black"
cmdline = "#FFFFFF"
cmdline_bg = "#444444"

[keybindings]
"Shift+q" = "focus queue"
"Shift+l" = "focus library"
"/" = "focus search"
