# add system-wide php configuration options here
memory_limit = 1G
max_execution_time = 0
max_input_time = -1
post_max_size = 64M
upload_max_filesize = 64M

; Fast code coverage driver (avoid Xdebug overhead)
extension="/opt/homebrew/opt/pcov@8.5/pcov.so"
