[default_session]
startup_command = "ide"

[[session]]
name = "dotfiles"
path = "~/dev/contrib/dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "home"
path = "~/"
startup_command = ""

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = ""
