[[session]]
name = "dotfiles"
path = "~/dev/contrib/dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "notes"
path = "~/Nextcloud/Documents/notes"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "home"
path = "~/"
startup_command = "cd notes;tmux split-window -h -l 50%;tmux select-pane -L;nvim -c ':Telescope find_files'"

[[session]]
name = "downloads"
path = "~/Downloads"
disable_startup_command = true

[default_session]
startup_command = "ide"
