[default_session]
startup_command = "ide"

[[session]]
name = "home"
path = "~/"

[[session]]
name = "downloads"
path = "~/Downloads"

[[session]]
name = "dotfiles"
path = "~/dev/contrib/dotfiles"
startup_command = "nvim -c ':Telescope find_files'"
