vim.bo.commentstring = '<!-- %s -->'
vim.opt_local.spell = true
vim.opt.conceallevel = 0
vim.wo.conceallevel = 0
vim.opt.number = false
vim.opt.relativenumber = false
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
