#!/bin/bash
not_in_tmux() {
    [ -z "$TMUX" ]
}

session_name="notes"
path_name="$HOME/doc/notes/"

session_exists() {
    # checks if the $session_name exists
    tmux has-session -t "=$session_name"
}

create_detached_session() {
    if [ "$DIR" == "--start" ]; then
        (
        TMUX=''
        tmux new-session -Ad -s "$session_name" -c $path_name
    )
else
    (
    TMUX=''
    tmux new-session -Ad -s "$session_name" -c $path_name
    tmux send-keys -t "$session_name" "nvim index.md" Enter
)
    fi
}

create_if_needed_and_attach() {
    if not_in_tmux; then
        tmux new-session -A -s "$session_name" -c $path_name
    else
        if ! session_exists; then
            create_detached_session
        fi
        tmux switch-client -t "$session_name"
    fi
}

attatch_to_first_session() {
    tmux attach -t $(tmux list-sessions -F "${session_name}" | head -n 1)
    tmux choose-tree -Za
}

create_if_needed_and_attach || attatch_to_first_session
