#!/bin/sh

# use coreutils `ls` if possible…
hash gls >/dev/null 2>&1 || alias gls="ls"

# always use color, even when piping (to awk,grep,etc)
if gls --color >/dev/null 2>&1; then colorflag="--color"; else colorflag="-G"; fi
export CLICOLOR_FORCE=1

# Bookmarks
alias w="t ~/dev/www"
alias notes="nvim ~/Library/CloudStorage/OneDrive-Metech,TransformaciónDigital/notes/index.md"
alias v="fd --type f --hidden --exclude .git | fzf-tmux -p --reverse | xargs nvim"
alias help='tldr --list | fzf --preview "tldr {1}" --preview-window=right,70% | xargs tldr'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
# alias rm='trash-put'

# easier to read disk
alias df='df -h' # human-readable sizes

# Recursively delete `.DS_Store` files
alias dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# Shortcuts
alias vim="nvim"
alias vi="nvim"

# Update installed Ruby gems, Homebrew, npm, and their installed packages
alias brewupdate="brew -v update; brew upgrade --force-bottle; brew cleanup; brew doctor"
alias composerupdate='composer global update'
alias npmupdate='composer global update; npm -g update; npm -g upgrade; npm cache clean --force'
# zeoxide, zsh y tmux
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# ImageOptim, se puede usar . o nombre de archivo
alias imageoptim="open -a ImageOptim"

# Python
alias python='/opt/homebrew/bin/python3'

# PHP
alias php82='/opt/homebrew/opt/php@8.2/bin/php'
alias php81='/opt/homebrew/opt/php@8.1/bin/php'
alias php80='/opt/homebrew/opt/php@8.0/bin/php'
alias php7='/opt/homebrew/opt/php@7.4/bin/php'

# Laravel Sail & Artisan
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'

# less con color
alias less='less -r'

# executables
alias ls='exa -al --color=always --group-directories-first'
alias lt='exa -aT --color=always --group-directories-first'
alias cat='bat --plain --wrap character'

# spotify ncurses
alias spotify='ncspot'

# Logout para xfce
if [ "$DESKTOP_SESSION" = "xfce" ]; then
    alias shutdown='xfce4-session-logout --halt'
    alias reboot='xfce4-session-logout --reboot'
    alias suspend='xfce4-session-logout --suspend'
    alias hibernate='xfce4-session-logout --hibernate'
    alias lock='xfce4-session-logout --lock-screen'
    alias logout='xfce4-session-logout --logout'
fi
