#!/bin/sh

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

if [[ $(uname) == "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)" # This loads brew on M1
    eval "$(zoxide init zsh)"                 # This loads zoxide
    eval "$(nodenv init -)"                   # This loads nodenv

    # source "$HOME/.cargo/env"

    export PATH="/opt/homebrew/bin":$PATH
    export PATH="/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin":$PATH
fi

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.composer/vendor/bin":$PATH
