#!/bin/sh

# use coreutils `ls` if possible…
hash gls >/dev/null 2>&1 || alias gls="ls"

# always use color, even when piping (to awk,grep,etc)
if gls --color >/dev/null 2>&1; then colorflag="--color"; else colorflag="-G"; fi
export CLICOLOR_FORCE=1

# Bookmarks
alias help='tldr --list | fzf --preview "tldr {1}" --preview-window=right,70% | xargs tldr'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colorize diff output
alias diff='diff --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -iv'

# i can't remove vim in mac
alias vim='nvim'

# Recursively delete `.DS_Store` files
alias dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# Update installed Homebrew, npm, composer and zsh
alias brew-update="brew -v update; brew upgrade --force-bottle; brew cleanup; brew doctor"
alias composer-update='composer global update'
alias npm-update='npm -g update; npm -g upgrade; npm cache clean --force'
# zeoxide, zsh y tmux
alias zsh-update="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# ImageOptim, se puede usar . o nombre de archivo
alias imageoptim="open -a ImageOptim"

# Python
alias python='/opt/homebrew/bin/python3'

# PHP
alias php83='/opt/homebrew/opt/php@8.2/bin/php'
alias php82='/opt/homebrew/opt/php@8.2/bin/php'
alias php81='/opt/homebrew/opt/php@8.1/bin/php'
alias php80='/opt/homebrew/opt/php@8.0/bin/php'
alias php7='/opt/homebrew/opt/php@7.4/bin/php'

# Symfony
alias sc='symfony console'

# less con color
alias less='less -r'

# executables
alias ls='ls --color=auto'
alias ll='ls -lAF'
alias cat='bat --plain --wrap character'

# spotify ncurses
alias spotify='spotify_player'
#weather
alias weather='curl wttr.in/Madrid'

# start nodenv
alias nodenv-start='eval "$(nodenv init -)"'

# Logout para xfce
if [ "$DESKTOP_SESSION" = "xfce" ]; then
    alias shutdown='xfce4-session-logout --halt'
    alias reboot='xfce4-session-logout --reboot'
    alias suspend='xfce4-session-logout --suspend'
    alias hibernate='xfce4-session-logout --hibernate'
    alias lock='xfce4-session-logout --lock-screen'
    alias logout='xfce4-session-logout --logout'
fi

# Zoxide
alias cd="z"

# Yazi
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
