#!/bin/sh

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

eval "$(/opt/homebrew/bin/brew shellenv)" # This loads brew on M1
eval "$(zoxide init zsh)"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin:$PATH

source $(brew --prefix php-version)/php-version.sh # Incializa php-versions
php-version 8.1 # Set PHP version
