# OPTIONS ========================================
setopt AUTOCD EXTENDEDGLOB MENUCOMPLETE NOMATCH
setopt BANG_HIST              # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY       # Write the history file in the ':start:elapsed;command' format.
setopt INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits.
setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS       # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS   # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display a previously found event.
setopt HIST_IGNORE_SPACE      # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS      # Do not write a duplicate event to the history file.
setopt HIST_VERIFY            # Do not execute immediately upon history expansion.
setopt HIST_BEEP              # Beep when accessing non-existent history.
setopt SHARE_HISTORY

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
stty stop undef # Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')
zle-line-init() {
  if [[ "$ZLE_LOCAL_HISTORY_SET" != "1" ]]; then
    ZLE_LOCAL_HISTORY_SET=1
    zle set-local-history 1
  fi
}
zle -N zle-line-init

# beeping is annoying
unsetopt BEEP

# Reevaluate the prompt string each time it's displaying a prompt
# setopt prompt_subst
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# autoload bashcompinit && bashcompinit
# autoload -Uz compinit
# compinit

# Colors
# autoload -Uz colors && colors

# EXPORTS ========================================
export EDITOR=nvim
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.composer/vendor/bin":$PATH
# macos specific stuff
if [[ $(uname) == "Darwin" ]]; then
    export PATH="/opt/homebrew/bin":$PATH
    export PATH="/opt/homebrew/sbin:$PATH"
    export PATH="/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin":$PATH
    export PATH="/opt/homebrew/opt/mariadb/bin:$PATH"
    export PATH="/opt/homebrew/opt/php@8.3/bin:$PATH"
fi

# zoxide
eval "$(zoxide init zsh)"
# nodenv
eval "$(nodenv init -)"
# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"
# starship
if [[ "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select" || \
      "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select-wrapped" ]]; then
    zle -N zle-keymap-select "";
fi

eval "$(starship init zsh)"

# ALIASES ========================================
source $ZDOTDIR/zsh-aliases

# FZF ========================================
source $ZDOTDIR/zsh-fzf

# ZSH PLUGINS ========================================
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# KEYBINDINGS ============================================
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
bindkey '^y' autosuggest-accept

dedupe
